spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
spring,jpa:
  ddl: update
